### ISSUE TITLE
Installed capacity when force_r is false

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#77] opened 2017-10-27 14:24 UTC
Hello,

I have a remark regarding the value of e_cap when force_r is false.
I am using a PV to supply a power demand.
First example: force_r=true
![force_r true](https://user-images.githubusercontent.com/29625919/32108177-21574f8a-bb31-11e7-880d-ab160200e943.png)
![cap-force_r true](https://user-images.githubusercontent.com/29625919/32108180-23e3050a-bb31-11e7-8ab1-e5b257133470.png)
Second example: force_r=false
![force_r false](https://user-images.githubusercontent.com/29625919/32108197-33ff4214-bb31-11e7-81ba-86c9b5431343.png)
![cap-force_r false](https://user-images.githubusercontent.com/29625919/32108198-3585c5ea-bb31-11e7-9d2c-aa65a9ee8412.png)

As I understand it, force_r gives the obligation to the technology to use all the resource.

As could be seen when force_r =true, the production on the second day peaks at 250KW whereas the maximum production over the considered period is around 350kW. But when using force_r = false, the production of the second day is almost equal to 370kW.
For me this means that the installed capacity when force_r=false is 50% higher than the one when force_r=true, to allow the second day to reach a higher value.

However, the installed capacity don't show such difference (350 vs 400kW). This is important because it means the e_cap value is maybe not the good one when e_cap=false.

**Comment by brynpickering** [comment] 2017-10-30 11:42
You're going to see strange things occur when you don't set realistic constraints for a technology! 
I imagine this has been caused by a lack of the constraint `r_area_per_e_cap`. The issue is with the two ends of a supply technology being essentially disconnected. With `force_r = false` you can get away with producing a lot of resource with free choice on how much you make use of. This means that `e_cap` and `r_cap` (i.e. `r_area`) don't necessarily match. For a system that uses a fuel, this might be OK, but it just isn't physically valid for PV.

First, let me know if `r_area_per_e_cap` was set for your problem, then we can go from there. per kWp, you're looking at about 7m2 of panel (`r_area_per_e_cap: 7`).

**Comment by arnaud-leroy** [comment] 2017-10-30 13:39
Ok it works too!
Thanks for the quick answer :)

**Comment by brynpickering** [comment] 2017-10-30 14:41
No problem! We should probably build up a library of technologies, which have all the relevant constraints defined, to avoid this confusion in future.

**Comment by arnaud-leroy** [comment] 2017-10-30 16:04
Ok there is still something i don't get with r_area and e_cap.
`r_area.max` is the maximum superficy for a technology and `e_cap.max` is the max installed capacity.
r_area and e_cap are linked with the area used per installed capacity `r_area_per_e_cap`.

I have done some tries: I expected to eventually see the installed capacity decrease when I increased `r_area_per_e_cap`: the higher the required area per kW, the more likely we are to hit `r_area.max`... but the opposite happened and I can't understand why.

I used the following parameters:
-in locations.yaml, for the considered location, i put `available_area: 3500.0`
-in techs.yaml, I used the following values, with `r_area_per_e_cap` changing from 0.4 to 40 to see the impact of this parameter
```
    constraints:
      e_cap.max: 2999
      r: 0.0
      r_area.max: 2999
      r_area_per_e_cap: 7
```

for r_area_per_e_cap: 7, the installed capacity is 762. it is below e_cap.max, but 7*762=5334>r_area.max and available_area
for r_area_per_e_cap: 40, the installed capacity is 500, which is the maximal power generation but can't be the capacity because my PV file never got a value equal to 1. the curve is just below
![force_r new](https://user-images.githubusercontent.com/29625919/32181160-01272dba-bd94-11e7-9403-81030253b1f1.png)
for r_area_per_e_cap: 0.4, the installed capacity is 0.

Do you have an idea of why it behaves like that?
Thanks,
Arnaud

**Comment by brynpickering** [comment] 2017-10-30 19:33
Taking a look at the constraints, the existence of r_area_per_e_cap supersedes r_area.max:

```
    def c_r_area_rule(m, loc_tech):
        """
        Set maximum r_area. Supply_plus techs only.
        """
        y, x = get_y_x(loc_tech)
        area_per_cap = model.get_option(y + '.constraints.r_area_per_e_cap', x=x)
        if area_per_cap:
            return m.r_area[loc_tech] == m.e_cap[loc_tech] * area_per_cap
        else:
            e_cap_max = model.get_option(y + '.constraints.e_cap.max', x=x)
            if e_cap_max == 0:
                # If a technology has no e_cap here, we force r_area to zero,
                # so as not to accrue spurious costs
                return m.r_area[loc_tech] == 0
            else:
                return get_var_constraint(m.r_area[loc_tech], y, 'r_area', x)
``` 

i.e. if you specify it, r_area.max constraints are ignored. In the latest dev release I've split this into two constraints, such that maximum r_area and the connection between e_cap and r_area are both retained. Let me know if there is an improvement here.

However, available_area shouldn't be exceeded in your current model. Remember that available_area constraint is optional, so you have to initialise it in optional constraints.

**Comment by arnaud-leroy** [comment] 2017-10-31 09:01
ok for r_area max, I made it work. Thanks for your help :) I will get it in the end ;)

I still got an issue with the generation profile which is still not realistic when compared with the installed capacity.

Another example to try to make it clear: I have set the available_area at 1500 and r_area_per_e_cap at 5. This is the corresponding generation profile
![e_cap_t](https://user-images.githubusercontent.com/29625919/32214506-629114a4-be1f-11e7-898e-a583b7677c21.png)

The installed capacity
![e_cap](https://user-images.githubusercontent.com/29625919/32214510-643e0aaa-be1f-11e7-9a09-694541de04ad.png)

and the PV profile used as an input
![pv profile](https://user-images.githubusercontent.com/29625919/32214311-b280be34-be1e-11e7-80cc-a7514fd94655.png)

The installed capacity is 1500/5=300. That is exactly what it should be! 
However we could see on the PV profile that the first day has a higher maximum capacity factor than the other days, but it is not seen in the generation profile: except for day 2, every day reaches a max of 300. 
Also with a maximum capacity factor close to 0.3 on the considered period, I don't understand how the maximum generation could reach 300. The max of the generation should be around 90 (1500/5x0.3) for day one, 30 (1500/5x0.1) for day 2, around 75 for day 3 (1500/5x0.25) and 60 (1500/5x0.2) for day 4 and 5, no?

Or is the r file not the capacity factor but something different? And if yes, is it possible to use it as a capacity factor?

**Comment by brynpickering** [comment] 2017-10-31 09:58
The information in your csv file should be kwh/m2, not kWh/kWp (capacity factor), as it is multiplied by area to give you your available resource across the area for which you have purchased panels. It still does not explain the issue, as setting `force_r`, `available_area` and `r_area_per_e_cap` should mean that once an `r_area` (and reciprocally an `e_cap`) have been assigned, the output of the panel is fixed to follow the available resource. Did you set `force_r` here? Also, are there any losses assigned to the technology?

**Comment by arnaud-leroy** [comment] 2017-10-31 10:54
Thanks, for your answer, it is getting clearer!
no I had these results without setting force_r. If I put `force_r: true`, no PV is installed.

**Closed** 2018-04-06 13:46 UTC
Labels: discussion, possibly-revisit
