### ISSUE TITLE
Error in parsing dates in timeseries data

### ISSUE THREAD

**Issue by mohammadamint** [calliope-project/calliope#276] opened 2019-08-08 09:52 UTC
I get the following error:

ModelError: Error in parsing dates in timeseries data from Hydro_Amin.csv, using datetime format `%Y-%m-%d %H:%M:%S`: time data 1/1/2005 0:00 doesn't match format specified

I have tried also with the tutorial csv files by changing the data, but I get the same error!!!!

**Comment by Ewanfrostpennington** [comment] 2019-08-09 08:26
You need to change the format to "%d/%m/%Y %H:%M" currently you are putting the year first in the format but in your csv its the other way round

**Comment by mohammadamint** [comment] 2019-08-10 13:57
Many thanks for your answer.

I tried to change the time format in csv file but it doesnt work till the windows time and data format be the same with %Y-%m-%d %H:%M:%S !!

**Comment by brynpickering** [comment] 2019-08-12 06:38
@Ewanfrostpennington is right that you need the timeseries format to be "%d/%m/%Y %H:%M", based on your data (`model.timeseries_dateformat: "%d/%m/%Y %H:%M"`). The problem is that if you open a CSV with Excel, it will automatically set the timeseries format to the Windows timeseries format on opening the CSV. The best bet is to either change the Windows format (as it seems you've done) or open the CSV in a text editor, not in Excel (e.g. VScode).

I'm going to close this, as it doesn't seem to be an issue of Calliope. You can reopen it if setting the timeseries format to "%d/%m/%Y %H:%M" doesn't work when your data timeseries format is "%d/%m/%Y %H:%M".

**Closed by brynpickering** 2019-08-12 06:38 UTC
